---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: ubi9-py39-sample-1 # TODO
  labels:
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CRE-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: ubi9py39-1
    opendatahub.io/notebook-image-desc: Build using a list of packages, ontop a UBI9 Python 3.9 base image
    opendatahub.io/notebook-image-creator: codificat
spec:
  buildType: PackageList
  runtimeEnvironment:
    osName: rhel
    osVersion: "9"
    pythonVersion: "3.9"
  packageVersions:
    - "pandas"
