---
apiVersion: meteor.zone/v1alpha1
kind: CustomRuntimeEnvironment
metadata:
  name: s2i-minimal-py38-sample-1 # TODO
  labels:
    # Orignal, : and / need to be replaced! app.kubernetes.io/created-by: cpe:/a:meteor.zone:CRE:v0.1.0
    app.kubernetes.io/created-by: cpe-_a-meteor.zone-CRE-v0.1.0
  annotations:
    opendatahub.io/notebook-image-name: py38-1
    opendatahub.io/notebook-image-desc: Build using a S2I Python 3.8 image and a list of packages
    opendatahub.io/notebook-image-creator: codificat
spec:
  buildType: PackageList
  baseImage: quay.io/thoth-station/s2i-minimal-py38-notebook:v0.2.2
  packageVersions:
    - pandas
    - boto3>=1.24.0
